const seed={customers:[{id:1,name:'علي كريم',phone:'0770 123 4567',points:1280,tier:'ذهبي',branch:'الكرادة',visits:18,last:'اليوم'},{id:2,name:'سارة أحمد',phone:'0781 222 9034',points:860,tier:'فضي',branch:'المنصور',visits:11,last:'أمس'},{id:3,name:'حيدر عباس',phone:'0750 784 1122',points:430,tier:'أساسي',branch:'الجادرية',visits:6,last:'منذ 3 أيام'},{id:4,name:'نور حسين',phone:'0773 551 9081',points:1710,tier:'ذهبي',branch:'زيونة',visits:23,last:'اليوم'}],rewards:[{id:1,name:'قهوة مجانية',cost:500,status:'نشطة',redeemed:164},{id:2,name:'خصم 20%',cost:900,status:'نشطة',redeemed:97},{id:3,name:'وجبة مجانية',cost:1500,status:'نشطة',redeemed:65}],campaigns:[{id:1,name:'عودة العملاء',channel:'WhatsApp',audience:'غير النشطين 30 يوم',status:'نشطة',sent:328},{id:2,name:'مكافأة نهاية الأسبوع',channel:'WhatsApp',audience:'جميع العملاء',status:'مسودة',sent:0},{id:3,name:'عملاء VIP',channel:'WhatsApp',audience:'الفئة الذهبية',status:'مجدولة',sent:76}],branches:[{id:1,name:'فرع الكرادة',city:'بغداد',manager:'أحمد سعد',status:'نشط',customers:428},{id:2,name:'فرع المنصور',city:'بغداد',manager:'محمد علي',status:'نشط',customers:337},{id:3,name:'فرع الجادرية',city:'بغداد',manager:'زينب كريم',status:'نشط',customers:291},{id:4,name:'فرع زيونة',city:'بغداد',manager:'حسين عباس',status:'نشط',customers:192}],team:[{id:1,name:'ياسر',role:'مدير الحساب',branch:'كل الفروع',status:'نشط'},{id:2,name:'أحمد سعد',role:'مدير فرع',branch:'الكرادة',status:'نشط'},{id:3,name:'محمد علي',role:'كاشير',branch:'المنصور',status:'نشط'}],transactions:[{type:'إضافة',customer:'علي كريم',points:120,date:'اليوم 12:40'},{type:'استبدال',customer:'نور حسين',points:-500,date:'اليوم 11:15'},{type:'إضافة',customer:'سارة أحمد',points:80,date:'أمس 19:30'}],settings:{points:true,whatsapp:false,multibranch:true,autoTier:true}};
let state=JSON.parse(localStorage.getItem('loyaltyDemoState')||'null')||seed;
const save=()=>localStorage.setItem('loyaltyDemoState',JSON.stringify(state));
const content=document.getElementById('content'),pageTitle=document.getElementById('pageTitle'),eyebrow=document.getElementById('eyebrow'),modal=document.getElementById('modalBackdrop');
function fmt(n){return Number(n).toLocaleString('en-US')}
function badge(t){return `<span class="badge ${t==='نشط'||t==='نشطة'?'success':t==='مسودة'?'muted-badge':''}">${t}</span>`}
function actionBtn(txt,fn,cls='secondary'){return `<button class="${cls}" onclick="${fn}">${txt}</button>`}
function customerTable(rows){return `<div class="table-wrap"><table><thead><tr><th>العميل</th><th>الهاتف</th><th>النقاط</th><th>الفئة</th><th>الفرع</th><th>الزيارات</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${x.name}</b><small class="row-sub">${x.last||''}</small></td><td>${x.phone}</td><td><b>${fmt(x.points)}</b></td><td>${badge(x.tier)}</td><td>${x.branch}</td><td>${x.visits||0}</td><td><button class="table-action" onclick="openCustomer(${x.id})">عرض</button></td></tr>`).join('')}</tbody></table></div>`}
function openModal(title,body){document.querySelector('.modal').innerHTML=`<button class="modal-close" onclick="closeModal()">×</button><h3>${title}</h3>${body}`;modal.classList.add('show')}
window.closeModal=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)closeModal()};
window.openAddCustomer=()=>openModal('إضافة عميل جديد',`<form onsubmit="addCustomer(event)" class="form-grid"><label>اسم العميل<input name="name" required></label><label>رقم الهاتف<input name="phone" required placeholder="07xx xxx xxxx"></label><label>الرصيد الافتتاحي<input name="points" type="number" min="0" value="100"></label><label>الفرع<select name="branch">${state.branches.map(b=>`<option>${b.name.replace('فرع ','')}</option>`).join('')}</select></label><button class="primary wide span-2">إضافة العميل</button></form>`);
window.addCustomer=e=>{e.preventDefault();const f=new FormData(e.target);state.customers.unshift({id:Date.now(),name:f.get('name'),phone:f.get('phone'),points:+f.get('points')||0,tier:'أساسي',branch:f.get('branch'),visits:0,last:'الآن'});save();closeModal();switchView('customers')};
window.openCustomer=id=>{const c=state.customers.find(x=>x.id===id);openModal(c.name,`<div class="customer-profile"><div class="avatar-lg">${c.name[0]}</div><div><b>${c.phone}</b><div class="muted">${c.branch} • ${c.visits} زيارة</div></div></div><div class="profile-stats"><div><small>الرصيد</small><strong>${fmt(c.points)}</strong></div><div><small>الفئة</small><strong>${c.tier}</strong></div></div><div class="quick-actions"><button class="primary" onclick="adjustPoints(${c.id},true)">+ إضافة نقاط</button><button class="secondary" onclick="adjustPoints(${c.id},false)">− خصم نقاط</button><button class="secondary" onclick="issueCard(${c.id})">إصدار بطاقة</button></div>`)};
window.adjustPoints=(id,add)=>{const c=state.customers.find(x=>x.id===id);openModal(add?'إضافة نقاط':'خصم نقاط',`<form onsubmit="applyPoints(event,${id},${add})"><p class="muted">العميل: ${c.name} — الرصيد الحالي ${fmt(c.points)} نقطة</p><label>عدد النقاط<input name="pts" type="number" min="1" required value="100"></label><label>ملاحظة<input name="note" placeholder="مثال: فاتورة شراء"></label><button class="primary wide">تأكيد العملية</button></form>`)};
window.applyPoints=(e,id,add)=>{e.preventDefault();const pts=+new FormData(e.target).get('pts');const c=state.customers.find(x=>x.id===id);c.points=Math.max(0,c.points+(add?pts:-pts));state.transactions.unshift({type:add?'إضافة':'خصم',customer:c.name,points:add?pts:-pts,date:'الآن'});save();closeModal();switchView('customers')};
window.issueCard=id=>{const c=state.customers.find(x=>x.id===id);openModal('تم تجهيز البطاقة',`<div class="loyalty-card compact"><small>منصة ولاء • قهوة بغداد</small><h3>${c.name}</h3><div class="points">${fmt(c.points)} <small>نقطة</small></div><div>رقم العضوية •••• ${String(c.id).slice(-4)}</div></div><p class="muted">هذه معاينة Frontend. لاحقاً يتم إنشاء Google Wallet / Apple Wallet Pass حقيقي من الـBackend.</p><button class="primary wide" onclick="closeModal()">تم</button>`)};
window.addReward=()=>openModal('إضافة مكافأة',`<form onsubmit="saveReward(event)" class="form-grid"><label>اسم المكافأة<input name="name" required></label><label>تكلفة النقاط<input name="cost" type="number" min="1" required></label><button class="primary span-2">حفظ المكافأة</button></form>`);
window.saveReward=e=>{e.preventDefault();const f=new FormData(e.target);state.rewards.unshift({id:Date.now(),name:f.get('name'),cost:+f.get('cost'),status:'نشطة',redeemed:0});save();closeModal();switchView('rewards')};
window.redeemReward=id=>{const r=state.rewards.find(x=>x.id===id);openModal('استبدال مكافأة',`<form onsubmit="doRedeem(event,${id})"><label>اختر العميل<select name="customer">${state.customers.map(c=>`<option value="${c.id}">${c.name} — ${fmt(c.points)} نقطة</option>`).join('')}</select></label><p class="muted">المكافأة: ${r.name} • ${fmt(r.cost)} نقطة</p><button class="primary wide">تنفيذ الاستبدال</button></form>`)};
window.doRedeem=(e,id)=>{e.preventDefault();const r=state.rewards.find(x=>x.id===id),c=state.customers.find(x=>x.id===+new FormData(e.target).get('customer'));if(c.points<r.cost){alert('رصيد العميل غير كافٍ');return}c.points-=r.cost;r.redeemed++;state.transactions.unshift({type:'استبدال',customer:c.name,points:-r.cost,date:'الآن'});save();closeModal();switchView('rewards')};
window.addCampaign=()=>openModal('إنشاء حملة',`<form onsubmit="saveCampaign(event)" class="form-grid"><label>اسم الحملة<input name="name" required></label><label>القناة<select name="channel"><option>WhatsApp</option><option>SMS</option><option>Push</option></select></label><label class="span-2">الجمهور<select name="audience"><option>جميع العملاء</option><option>الفئة الذهبية</option><option>غير النشطين 30 يوم</option><option>عملاء فرع محدد</option></select></label><label class="span-2">الرسالة<textarea name="message" required placeholder="اكتب رسالة الحملة..."></textarea></label><button class="primary span-2">حفظ كمسودة</button></form>`);
window.saveCampaign=e=>{e.preventDefault();const f=new FormData(e.target);state.campaigns.unshift({id:Date.now(),name:f.get('name'),channel:f.get('channel'),audience:f.get('audience'),status:'مسودة',sent:0});save();closeModal();switchView('campaigns')};
window.launchCampaign=id=>{const x=state.campaigns.find(c=>c.id===id);x.status='نشطة';x.sent=Math.max(x.sent,state.customers.length);save();switchView('campaigns')};
window.addBranch=()=>openModal('إضافة فرع',`<form onsubmit="saveBranch(event)" class="form-grid"><label>اسم الفرع<input name="name" required></label><label>المدينة<input name="city" value="بغداد" required></label><label class="span-2">مدير الفرع<input name="manager" required></label><button class="primary span-2">إضافة الفرع</button></form>`);
window.saveBranch=e=>{e.preventDefault();const f=new FormData(e.target);state.branches.push({id:Date.now(),name:'فرع '+f.get('name').replace('فرع ',''),city:f.get('city'),manager:f.get('manager'),status:'نشط',customers:0});save();closeModal();switchView('branches')};
window.addTeam=()=>openModal('إضافة موظف',`<form onsubmit="saveTeam(event)" class="form-grid"><label>الاسم<input name="name" required></label><label>الدور<select name="role"><option>مدير فرع</option><option>كاشير</option><option>مسؤول تسويق</option></select></label><label class="span-2">الفرع<select name="branch">${state.branches.map(b=>`<option>${b.name.replace('فرع ','')}</option>`).join('')}</select></label><button class="primary span-2">إضافة الموظف</button></form>`);
window.saveTeam=e=>{e.preventDefault();const f=new FormData(e.target);state.team.push({id:Date.now(),name:f.get('name'),role:f.get('role'),branch:f.get('branch'),status:'نشط'});save();closeModal();switchView('team')};
window.toggleSetting=k=>{state.settings[k]=!state.settings[k];save();switchView('settings')};
window.resetDemo=()=>{if(confirm('إرجاع جميع بيانات النسخة التجريبية للوضع الأصلي؟')){state=JSON.parse(JSON.stringify(seed));save();switchView('dashboard')}};
const views={
dashboard:()=>`<div class="hero"><div><span class="hero-kicker">برنامج الولاء • قهوة بغداد</span><h2>أهلاً بك في منصة ولاء</h2><p>جرّب إدارة العميل من التسجيل إلى إصدار البطاقة وتجميع النقاط واستبدال المكافآت وإرسال الحملات.</p></div><div class="hero-actions"><button class="primary light" onclick="openAddCustomer()">+ إضافة عميل</button><button class="ghost-light" onclick="switchView('cards')">إصدار بطاقة</button></div></div><div class="stats"><div class="stat"><small>إجمالي العملاء</small><strong>${fmt(state.customers.length+1244)}</strong><span>↑ 8.4% هذا الشهر</span></div><div class="stat"><small>النقاط الحالية</small><strong>${fmt(state.customers.reduce((s,c)=>s+c.points,0)+44340)}</strong><span>ضمن كل الفروع</span></div><div class="stat"><small>المكافآت المستبدلة</small><strong>${fmt(state.rewards.reduce((s,r)=>s+r.redeemed,0))}</strong><span>↑ 12% عن الشهر السابق</span></div><div class="stat"><small>الفروع النشطة</small><strong>${state.branches.length}</strong><span>جميعها متصلة</span></div></div><div class="grid-2"><div class="panel"><div class="panel-head"><h3>أحدث العملاء</h3><button class="link-btn" onclick="switchView('customers')">عرض الكل</button></div>${customerTable(state.customers.slice(0,4))}</div><div class="panel"><div class="panel-head"><h3>آخر الحركات</h3><button class="link-btn" onclick="switchView('reports')">التفاصيل</button></div><div class="activity-list">${state.transactions.slice(0,5).map(t=>`<div class="activity"><span class="activity-icon">${t.points>0?'+':'−'}</span><div><b>${t.customer}</b><small>${t.type} • ${t.date}</small></div><strong class="${t.points>0?'positive':'negative'}">${t.points>0?'+':''}${fmt(t.points)}</strong></div>`).join('')}</div></div></div>`,
customers:()=>`<div class="view-head"><div><h2>العملاء</h2><div class="muted">إدارة الأعضاء، الرصيد، الزيارات، والفئات</div></div><button class="primary" onclick="openAddCustomer()">+ عميل جديد</button></div><div class="toolbar"><input id="customerSearch" placeholder="بحث بالاسم أو الهاتف..." oninput="filterCustomers(this.value)"><span>${state.customers.length} عميل تجريبي</span></div><div class="panel" id="customerPanel">${customerTable(state.customers)}</div>`,
cards:()=>`<div class="view-head"><div><h2>البطاقات الرقمية</h2><div class="muted">معاينة وإصدار بطاقات الولاء</div></div><button class="primary" onclick="openCardChooser()">+ إصدار بطاقة</button></div><div class="cards-layout"><div class="loyalty-card big"><small>قهوة بغداد</small><h3>بطاقة الولاء الذهبية</h3><div class="points">1,280 <small>نقطة</small></div><div class="card-bottom"><span>علي كريم</span><span>•••• 4581</span></div></div><div class="panel"><h3>إعدادات البطاقة</h3><div class="setting-summary"><span>اسم البطاقة</span><b>بطاقة ولاء قهوة بغداد</b></div><div class="setting-summary"><span>اللون الرئيسي</span><b>أخضر داكن</b></div><div class="setting-summary"><span>طرق الإضافة</span><b>QR • Google Wallet • Apple Wallet</b></div><button class="secondary wide" onclick="openCardChooser()">إصدار لعميل</button></div></div><h3 class="section-title">بطاقات العملاء</h3><div class="cards-grid">${state.customers.map(c=>`<div class="mini-card"><div class="card-row"><div class="avatar">${c.name[0]}</div><div><h3>${c.name}</h3><p class="muted">${fmt(c.points)} نقطة • ${c.tier}</p></div></div><button class="secondary wide" onclick="issueCard(${c.id})">معاينة البطاقة</button></div>`).join('')}</div>`,
rewards:()=>`<div class="view-head"><div><h2>النقاط والمكافآت</h2><div class="muted">إدارة قواعد النقاط واستبدال المكافآت</div></div><button class="primary" onclick="addReward()">+ مكافأة جديدة</button></div><div class="grid-2"><div class="panel"><h3>قاعدة احتساب النقاط</h3><div class="rule-box"><strong>1 نقطة</strong><span>لكل</span><strong>1,000 د.ع</strong></div><p class="muted">هذه القاعدة للعرض ويمكن جعلها مختلفة لكل نشاط أو فرع لاحقاً.</p></div><div class="panel"><h3>استبدالات هذا الشهر</h3><div class="big-number">${fmt(state.rewards.reduce((s,r)=>s+r.redeemed,0))}</div><span class="muted">عملية استبدال</span></div></div><div class="cards-grid reward-grid">${state.rewards.map(r=>`<div class="mini-card"><div class="reward-top"><span class="reward-icon">🎁</span>${badge(r.status)}</div><h3>${r.name}</h3><div class="reward-cost">${fmt(r.cost)} <small>نقطة</small></div><p class="muted">تم استبدالها ${r.redeemed} مرة</p><button class="primary wide" onclick="redeemReward(${r.id})">تجربة الاستبدال</button></div>`).join('')}</div>`,
campaigns:()=>`<div class="view-head"><div><h2>الحملات</h2><div class="muted">استهداف العملاء برسائل وعروض مخصصة</div></div><button class="primary" onclick="addCampaign()">+ إنشاء حملة</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>الحملة</th><th>القناة</th><th>الجمهور</th><th>الحالة</th><th>تم الإرسال</th><th></th></tr></thead><tbody>${state.campaigns.map(c=>`<tr><td><b>${c.name}</b></td><td>${c.channel}</td><td>${c.audience}</td><td>${badge(c.status)}</td><td>${fmt(c.sent)}</td><td>${c.status==='مسودة'?`<button class="table-action" onclick="launchCampaign(${c.id})">تشغيل تجريبي</button>`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`,
branches:()=>`<div class="view-head"><div><h2>الفروع</h2><div class="muted">إدارة نقاط البيع ومتابعة نشاط كل فرع</div></div><button class="primary" onclick="addBranch()">+ فرع جديد</button></div><div class="cards-grid">${state.branches.map(b=>`<div class="mini-card branch-card"><div class="branch-head"><div class="branch-icon">⌂</div>${badge(b.status)}</div><h3>${b.name}</h3><p class="muted">${b.city}</p><div class="setting-summary"><span>مدير الفرع</span><b>${b.manager}</b></div><div class="setting-summary"><span>العملاء</span><b>${fmt(b.customers)}</b></div></div>`).join('')}</div>`,
team:()=>`<div class="view-head"><div><h2>الموظفون والصلاحيات</h2><div class="muted">تحكم بمن يستطيع إدارة العملاء والنقاط والحملات</div></div><button class="primary" onclick="addTeam()">+ موظف جديد</button></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>الموظف</th><th>الدور</th><th>الفرع</th><th>الحالة</th><th>الصلاحيات</th></tr></thead><tbody>${state.team.map(u=>`<tr><td><b>${u.name}</b></td><td>${u.role}</td><td>${u.branch}</td><td>${badge(u.status)}</td><td><span class="permission">${u.role==='مدير الحساب'?'كاملة':u.role==='مدير فرع'?'عملاء + نقاط + تقارير':'نقاط + استبدال'}</span></td></tr>`).join('')}</tbody></table></div></div>`,
reports:()=>`<div class="view-head"><div><h2>التقارير</h2><div class="muted">قراءة أداء برنامج الولاء وسلوك العملاء</div></div><button class="secondary" onclick="alert('في النسخة الكاملة سيتم تصدير PDF/Excel من الـBackend')">تصدير التقرير</button></div><div class="stats"><div class="stat"><small>معدل عودة العملاء</small><strong>64%</strong><span>+7% هذا الشهر</span></div><div class="stat"><small>متوسط الرصيد</small><strong>${fmt(Math.round(state.customers.reduce((s,c)=>s+c.points,0)/state.customers.length))}</strong><span>نقطة لكل عميل</span></div><div class="stat"><small>معدل الاستبدال</small><strong>18%</strong><span>من النقاط المكتسبة</span></div><div class="stat"><small>عملاء VIP</small><strong>${state.customers.filter(c=>c.tier==='ذهبي').length+74}</strong><span>عملاء نشطون</span></div></div><div class="grid-2"><div class="panel"><h3>النشاط خلال 7 أيام</h3><div class="fake-chart">${[42,68,55,82,70,96,78].map((v,i)=>`<div><span style="height:${v}%"></span><small>${['س','ح','ن','ث','ر','خ','ج'][i]}</small></div>`).join('')}</div></div><div class="panel"><h3>أداء الفروع</h3>${state.branches.map((b,i)=>`<div class="progress-row"><span>${b.name}</span><div class="progress"><i style="width:${[88,72,61,48,55][i]||55}%"></i></div><b>${[88,72,61,48,55][i]||55}%</b></div>`).join('')}</div></div><div class="panel mt"><h3>سجل الحركات</h3><div class="activity-list">${state.transactions.map(t=>`<div class="activity"><span class="activity-icon">${t.points>0?'+':'−'}</span><div><b>${t.customer}</b><small>${t.type} • ${t.date}</small></div><strong class="${t.points>0?'positive':'negative'}">${t.points>0?'+':''}${fmt(t.points)}</strong></div>`).join('')}</div></div>`,
integrations:()=>`<div class="view-head"><div><h2>التكاملات</h2><div class="muted">الخدمات الخارجية المخطط ربطها بالمنصة</div></div></div><div class="cards-grid integrations-grid"><div class="mini-card integration"><div class="integration-logo google">G</div><div><h3>Google Wallet</h3><p class="muted">إضافة بطاقة الولاء مباشرة إلى محفظة Google.</p></div><span class="badge">جاهز للربط لاحقاً</span><button class="secondary wide" onclick="alert('يحتاج Google Wallet Issuer Account والـBackend')">عرض المتطلبات</button></div><div class="mini-card integration"><div class="integration-logo apple"></div><div><h3>Apple Wallet</h3><p class="muted">إصدار Pass وتحديث النقاط على أجهزة iPhone.</p></div><span class="badge">جاهز للربط لاحقاً</span><button class="secondary wide" onclick="alert('يحتاج Apple Developer وPass Type ID وشهادة')">عرض المتطلبات</button></div><div class="mini-card integration"><div class="integration-logo wa">W</div><div><h3>WhatsApp</h3><p class="muted">إرسال إشعارات الرصيد والمكافآت والحملات.</p></div>${badge(state.settings.whatsapp?'نشط':'غير مفعل')}<button class="primary wide" onclick="toggleSetting('whatsapp')">${state.settings.whatsapp?'إيقاف تجريبي':'تفعيل تجريبي'}</button></div></div>`,
settings:()=>`<div class="view-head"><div><h2>الإعدادات</h2><div class="muted">تخصيص النشاط وبرنامج الولاء</div></div><button class="danger-link" onclick="resetDemo()">إعادة ضبط التجربة</button></div><div class="settings-grid"><div class="panel"><h3>إعدادات برنامج الولاء</h3>${settingRow('تفعيل النقاط','السماح بإضافة واستبدال النقاط','points')}${settingRow('ترقية الفئات تلقائياً','ترقية العميل حسب الرصيد والنشاط','autoTier')}${settingRow('السماح بتعدد الفروع','إدارة أكثر من فرع داخل النشاط','multibranch')}</div><div class="panel"><h3>الإشعارات والتكامل</h3>${settingRow('إشعارات WhatsApp','إرسال إشعار عند تغير الرصيد','whatsapp')}<div class="setting-summary"><span>العملة</span><b>الدينار العراقي (IQD)</b></div><div class="setting-summary"><span>اللغة</span><b>العربية — RTL</b></div><div class="setting-summary"><span>المنطقة الزمنية</span><b>Asia/Baghdad</b></div></div></div><div class="panel mt"><h3>النشاط التجاري</h3><div class="business-form"><label>اسم النشاط<input value="قهوة بغداد"></label><label>نوع النشاط<input value="مقهى ومطعم"></label><label>رقم الهاتف<input value="0770 000 0000"></label><button class="primary" onclick="alert('تم الحفظ تجريبياً')">حفظ التغييرات</button></div></div>`};
function settingRow(title,desc,key){return `<div class="switch-row"><div><b>${title}</b><div class="muted">${desc}</div></div><div class="switch ${state.settings[key]?'on':''}" onclick="toggleSetting('${key}')"><i></i></div></div>`}
window.filterCustomers=q=>{const x=state.customers.filter(c=>(c.name+c.phone).includes(q));document.getElementById('customerPanel').innerHTML=customerTable(x)};
window.openCardChooser=()=>openModal('إصدار بطاقة لعميل',`<div class="select-list">${state.customers.map(c=>`<button onclick="issueCard(${c.id})"><span>${c.name}</span><small>${fmt(c.points)} نقطة</small></button>`).join('')}</div>`);
window.switchView=function(v){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));pageTitle.textContent=document.querySelector(`.nav-item[data-view="${v}"]`)?.textContent||'لوحة التحكم';eyebrow.textContent=v==='dashboard'?'نظرة عامة':'إدارة المنصة';content.innerHTML=views[v]?views[v]():views.dashboard();document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})};
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>switchView(btn.dataset.view));document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('tenantBtn').onclick=()=>openModal('تبديل النشاط',`<div class="select-list"><button onclick="closeModal()"><span>قهوة بغداد</span><small>النشاط الحالي</small></button><button onclick="alert('هذا يوضح فكرة Multi-Tenant فقط في النسخة التجريبية')"><span>مطعم النخيل</span><small>نشاط تجريبي آخر</small></button></div>`);
switchView('dashboard');