const state={customers:[{name:'علي كريم',phone:'0770 123 4567',points:1280,tier:'ذهبي'},{name:'سارة أحمد',phone:'0781 222 9034',points:860,tier:'فضي'},{name:'حيدر عباس',phone:'0750 784 1122',points:430,tier:'أساسي'},{name:'نور حسين',phone:'0773 551 9081',points:1710,tier:'ذهبي'}]};
const content=document.getElementById('content'),pageTitle=document.getElementById('pageTitle'),eyebrow=document.getElementById('eyebrow');
const views={
 dashboard:()=>`<div class="hero"><div><h2>أهلاً بك في منصة ولاء</h2><p>واجهة تجريبية لإدارة العملاء، البطاقات الرقمية، النقاط والمكافآت والحملات من مكان واحد، مع تصور مبسط لبيئة متعددة الأنشطة.</p></div><button class="primary" onclick="openCustomerModal()">+ إضافة عميل</button></div><div class="stats"><div class="stat"><small>إجمالي العملاء</small><strong>${state.customers.length+1244}</strong><span>↑ 8.4% هذا الشهر</span></div><div class="stat"><small>النقاط الممنوحة</small><strong>48,620</strong><span>نشاط مستقر</span></div><div class="stat"><small>المكافآت المستبدلة</small><strong>326</strong><span>↑ 12% عن الشهر السابق</span></div><div class="stat"><small>الفروع النشطة</small><strong>4</strong><span>جميعها متصلة</span></div></div><div class="grid-2"><div class="panel"><div class="panel-head"><h3>أحدث العملاء</h3><button class="primary" onclick="switchView('customers')">عرض الكل</button></div>${customerTable(state.customers.slice(0,4))}</div><div class="panel"><div class="panel-head"><h3>المكافآت الأكثر طلباً</h3></div><div class="reward-list"><div class="reward"><span>قهوة مجانية</span><b>500 نقطة</b></div><div class="reward"><span>خصم 20%</span><b>900 نقطة</b></div><div class="reward"><span>وجبة مجانية</span><b>1,500 نقطة</b></div></div></div></div>`,
 customers:()=>`<div class="view-head"><div><h2>العملاء</h2><div class="muted">إدارة أعضاء برنامج الولاء ونشاطهم</div></div><button class="primary" onclick="openCustomerModal()">+ عميل جديد</button></div><div class="panel">${customerTable(state.customers)}</div>`,
 cards:()=>`<div class="view-head"><div><h2>البطاقات الرقمية</h2><div class="muted">تصميم وإصدار بطاقات الولاء للعملاء</div></div><button class="primary">إصدار بطاقة</button></div><div class="cards-grid"><div class="loyalty-card"><small>قهوة بغداد</small><h3>بطاقة الولاء الذهبية</h3><div class="points">1,280 <small>نقطة</small></div><div>علي كريم •••• 4581</div></div><div class="mini-card"><h3>Google Wallet</h3><p class="muted">جاهز لربط بطاقات العملاء مع Google Wallet عند إضافة التكامل الحقيقي.</p><span class="badge">مخطط للتكامل</span></div><div class="mini-card"><h3>Apple Wallet</h3><p class="muted">واجهة مهيأة لاحقاً لإضافة Passes بعد إعداد شهادة Apple Wallet.</p><span class="badge">مخطط للتكامل</span></div></div>`,
 rewards:()=>simpleCards('النقاط والمكافآت',[['قاعدة احتساب النقاط','1 نقطة لكل 1,000 د.ع'],['قهوة مجانية','500 نقطة'],['خصم 20%','900 نقطة'],['وجبة مجانية','1,500 نقطة']]),
 campaigns:()=>simpleCards('الحملات',[['حملة عودة العملاء','328 مستلم'],['مكافأة نهاية الأسبوع','جاهزة للإرسال'],['عملاء VIP','76 عميل']]),
 branches:()=>simpleCards('الفروع',[['فرع الكرادة','نشط'],['فرع المنصور','نشط'],['فرع الجادرية','نشط'],['فرع زيونة','نشط']]),
 team:()=>simpleCards('الموظفون والصلاحيات',[['مدير الحساب','صلاحيات كاملة'],['مدير فرع الكرادة','إدارة الفرع والعملاء'],['كاشير 01','إضافة نقاط واستبدال مكافآت']]),
 reports:()=>`<div class="view-head"><div><h2>التقارير</h2><div class="muted">ملخص سريع لأداء برنامج الولاء</div></div></div><div class="stats"><div class="stat"><small>معدل العودة</small><strong>64%</strong><span>+7%</span></div><div class="stat"><small>متوسط النقاط</small><strong>742</strong><span>لكل عميل</span></div><div class="stat"><small>الاستبدال</small><strong>18%</strong><span>من النقاط المكتسبة</span></div><div class="stat"><small>عملاء VIP</small><strong>76</strong><span>نشطون</span></div></div><div class="panel"><h3>ملاحظة</h3><p class="muted">في النسخة الكاملة يمكن إضافة مخططات يومية وشهرية، مقارنة الفروع، قيمة العميل، وتصدير PDF/Excel.</p></div>`,
 integrations:()=>`<div class="view-head"><div><h2>التكاملات</h2><div class="muted">ربط المنصة مع الخدمات الخارجية</div></div></div><div class="cards-grid"><div class="mini-card"><h3>Google Wallet</h3><p class="muted">إضافة بطاقة ولاء إلى محفظة Google.</p><span class="badge">قريباً</span></div><div class="mini-card"><h3>Apple Wallet</h3><p class="muted">إصدار Apple Pass للعملاء.</p><span class="badge">قريباً</span></div><div class="mini-card"><h3>WhatsApp</h3><p class="muted">إشعارات النقاط والمكافآت والحملات.</p><span class="badge">اختياري</span></div></div>`,
 settings:()=>`<div class="view-head"><div><h2>الإعدادات</h2><div class="muted">تخصيص النشاط وبرنامج الولاء</div></div></div><div class="panel"><div class="switch-row"><div><b>تفعيل النقاط</b><div class="muted">السماح بإضافة واستبدال النقاط</div></div><div class="switch on" onclick="this.classList.toggle('on')"><i></i></div></div><div class="switch-row"><div><b>إشعارات WhatsApp</b><div class="muted">إرسال إشعارات للعملاء عند تغير الرصيد</div></div><div class="switch" onclick="this.classList.toggle('on')"><i></i></div></div><div class="switch-row"><div><b>السماح بتعدد الفروع</b><div class="muted">إدارة أكثر من فرع داخل النشاط</div></div><div class="switch on" onclick="this.classList.toggle('on')"><i></i></div></div></div>`
};
function customerTable(rows){return `<div class="table-wrap"><table><thead><tr><th>العميل</th><th>الهاتف</th><th>النقاط</th><th>الفئة</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.phone}</td><td>${x.points.toLocaleString('en-US')}</td><td><span class="badge">${x.tier}</span></td></tr>`).join('')}</tbody></table></div>`}
function simpleCards(title,items){return `<div class="view-head"><div><h2>${title}</h2><div class="muted">بيانات تجريبية للمعاينة</div></div><button class="primary">+ إضافة جديد</button></div><div class="cards-grid">${items.map(([a,b])=>`<div class="mini-card"><h3>${a}</h3><p class="muted">${b}</p><span class="badge">نشط</span></div>`).join('')}</div>`}
function switchView(v){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));pageTitle.textContent=document.querySelector(`.nav-item[data-view="${v}"]`)?.textContent||'لوحة التحكم';eyebrow.textContent=v==='dashboard'?'نظرة عامة':'إدارة المنصة';content.innerHTML=views[v]?views[v]():views.dashboard();document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>switchView(btn.dataset.view));document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
const modal=document.getElementById('modalBackdrop');window.openCustomerModal=()=>modal.classList.add('show');document.getElementById('modalClose').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};
document.getElementById('customerForm').onsubmit=e=>{e.preventDefault();state.customers.unshift({name:customerName.value,phone:customerPhone.value,points:+customerPoints.value||0,tier:'أساسي'});modal.classList.remove('show');switchView('customers');e.target.reset()};
document.getElementById('tenantBtn').onclick=()=>alert('في النسخة الكاملة هنا يظهر اختيار الأنشطة/المستأجرين ضمن Multi-Tenant.');
switchView('dashboard');